services:
  postgres:
    container_name: course_postgres_db
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=course'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=secret'
    ports:
      - '5432:5432'